services:
  postgres:
    image: postgres:17.5
    container_name: wallet-db-restful
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wallet
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  wallet-main:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: wallet-app
        depends_on:
          postgres:
            condition: service_healthy
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_PROFILES_ACTIVE: ${SPRING_PROFILE:-dev}
        ports:
          - "8080:8080"
volumes:
  postgres_data:
